version: "3.8"

services:
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes # Enable persistence

  backend:
    build: ./backend
    ports:
      - "5000:5000"
      - "5500:5500"
    depends_on:
      - redis

    environment:
      - REDIS_URL=redis://redis:6379
    restart: unless-stopped
    env_file:
      - ./backend/.env

  frontend:
    build:
      context: ./frontend
      args:
        - VITE_API_URL=http://localhost:5000/api
        - VITE_SOCKET_URL=ws://localhost:5500
    ports:
      - "80:80"
    depends_on:
      - backend

    env_file:
      - ./frontend/.env
    restart: unless-stopped

volumes:
  redis_data:
